Categories:
 - Internet

License: MIT
AuthorName: Jica98
AuthorEmail: jica.etzc@gmail.com
AuthorWebSite: https://github.com/JICA98
SourceCode: https://github.com/JICA98/DailyAL.git
IssueTracker: https://github.com/JICA98/DailyAL/issues
AutoName: DailyAL 
RepoType: git
Repo: https://github.com/JICA98/DailyAL
Changelog: https://github.com/JICA98/DailyAL/blob/psycho/metadata/en-US/changelogs/89.txt

CurrentVersion: 2024.2.2
CurrentVersionCode: 89
AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: pubspec.yaml|version:\s.+\+(\d+)|.|version:\s(.+)\+

Builds:
    -   versionName: 2024.2.2
        versionCode: 89
        commit: 5a6ad7ba8247ae429a6f12a21f57a2c4fcfdd849
        output: build/app/outputs/flutter-apk/app-release.apk
        srclibs:
            - flutter@3.16.9
        prebuild:
            - export PUB_CACHE=$(pwd)/.pub-cache
            - $$flutter$$/bin/flutter config --no-analytics
            - $$flutter$$/bin/flutter pub get
        scandelete:
            - $(pwd)/.pub-cache
        build:
        - export PUB_CACHE=$(pwd)/.pub-cache
        - $$flutter$$/bin/flutter build apk --release
